### ISSUE TITLE
Changes to adapter.c in latest wine

### ISSUE THREAD

**Issue by SteveEbey73742** [SveSop/nVidia_vkd3d#1]
patching file dlls/dxgi/adapter.c
Hunk #1 FAILED at 297.
1 out of 1 hunk FAILED -- saving rejects to file dlls/dxgi/adapter.c.rej
that is what happens with latest wine source pulls from devel and staging.

**Comment by kakra** [comment]
Please look here: https://github.com/SveSop/nVidia_vkd3d/commit/fede76e5540a5208328dccf5e06979b4d3dd9085#commitcomment-31400658

**Comment by SveSop** [comment]
Wine-3.21 have the patch implemented, but i could not get it to work. Had to do a small change, but did not test more than seeing `D3d12 Device Create Successful` and getting graphics with that last change.

dd09100

**Comment by SveSop** [comment]
Closing this for now then, as it works with 3.21.

Will see if i can get some message back to the lutris team about their either confusing release tags, or bugged release tags :)
